@ShopApp_HostAddress = https://localhost:7250

GET {{ShopApp_HostAddress}}/api/product/get

###

GET {{ShopApp_HostAddress}}/api/items

###

GET {{ShopApp_HostAddress}}/api/items/40

### Lesson, test

POST https://e437-37-52-79-159.ngrok-free.app/api/product
Content-Type: application/json
{
  "Title": "Pie",
  "Price": 52.42
}

### Lesson, task

GET {{ShopApp_HostAddress}}/api/category