@ShopApp_HostAddress = https://localhost:7250

### Dz1

GET {{ShopApp_HostAddress}}/api/products

###

GET {{ShopApp_HostAddress}}/api/products/1

###

POST {{ShopApp_HostAddress}}/api/products
Content-Type: application/json
{
  "Title": "Laptop",
  "Price": 45000
}

###

PUT {{ShopApp_HostAddress}}/api/products/1
Content-Type: application/json
{
  "Title": "Laptop Pro",
  "Price": 55000.9
}

###

DELETE {{ShopApp_HostAddress}}/api/products/1

###

GET {{ShopApp_HostAddress}}/api/products/search?title=Laptop

### Dz5

GET {{ShopApp_HostAddress}}/api/category

###

GET {{ShopApp_HostAddress}}/api/category/2
